# secret-provider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fileprocessing-keyvault-secrets
  namespace: fileprocessingapi   
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "218d8785-25b2-4fbb-98fe-6c168c7a79b1"   # paste from step 3
    keyvaultName: "fileprocessing-prod-kv"
    tenantId: "c6152130-4f43-40ff-8b32-916293b0456f"            # az account show --query tenantId
    objects: |
      array:
        - |
          objectName: ConnectionStrings--Postgres
          objectType: secret
        - |
          objectName: Storage--AccountName
          objectType: secret
        - |
          objectName: ServiceBus--FullyQualifiedNamespace
          objectType: secret
  secretObjects:                            # syncs to a real k8s Secret
    - secretName: fileprocessing-prod-secrets
      type: Opaque
      data:
        - objectName: ConnectionStrings--Postgres
          key: ConnectionStrings__Postgres
        - objectName: Storage--AccountName
          key: Storage__AccountName
        - objectName: ServiceBus--FullyQualifiedNamespace
          key: ServiceBus__FullyQualifiedNamespace