FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    clang zlib1g-dev
WORKDIR /src
COPY ["FileProcessingApi/FileProcessingApi.csproj", "FileProcessingApi/"]
RUN dotnet restore "./FileProcessingApi/FileProcessingApi.csproj"
COPY . .
WORKDIR "/src/FileProcessingApi"
RUN dotnet build "./FileProcessingApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./FileProcessingApi.csproj" -c Release -o /app/publish /p:UseAppHost=true

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=publish /app/publish .
ENTRYPOINT ["./FileProcessingApi"]