<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>false</PublishAot>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.19.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileProcessingAppLogic\FileProcessingApplication.csproj" />
    <ProjectReference Include="..\FileProcessingPublisher\FileProcessingPublisher.csproj" />
    <ProjectReference Include="..\FileProcessingRepository\FileProcessingRepository.csproj" />
    <ProjectReference Include="..\FileProcessingStorage\FileProcessingStorage.csproj" />
  </ItemGroup>
  
</Project>
